local ReplicatedFirst = game:GetService("ReplicatedFirst")
local InstanceManager = require(ReplicatedFirst.Nexsys.Common.InstanceManager)
local LayoutManager = {}
----------------------------------------------------------------------------------------------------
-- ゲーム独自のレイアウト系処理(InstanceManagerから切り離す)
----------------------------------------------------------------------------------------------------

return LayoutManager
