local RunService = game:GetService("RunService")
local PathfindingService = game:GetService("PathfindingService")
local NavPathMove = {}
NavPathMove.__index = NavPathMove

local waypoints
local nextWaypointIndex
local reachedConnection
local blockedConnection

local function followPath(path, character : Model, destination : Vector3)
	local humanoid = character:FindFirstChildOfClass("Humanoid")
	if not humanoid then
		return
	end

	-- Compute the path
	local success, errorMessage = pcall(function()
		path:ComputeAsync(character.PrimaryPart.Position, destination)
	end)

	if success and path.Status == Enum.PathStatus.Success then
		-- Get the path waypoints
		waypoints = path:GetWaypoints()

		-- Detect if path becomes blocked
		blockedConnection = path.Blocked:Connect(function(blockedWaypointIndex)
			-- Check if the obstacle is further down the path
			if blockedWaypointIndex >= nextWaypointIndex then
				-- Stop detecting path blockage until path is re-computed
				blockedConnection:Disconnect()
				-- Call function to re-compute new path
				followPath(destination)
			end
		end)

		-- Detect when movement to next waypoint is complete
		if not reachedConnection then
			reachedConnection = humanoid.MoveToFinished:Connect(function(reached)
				if reached and nextWaypointIndex < #waypoints then
					-- Increase waypoint index and move to next waypoint
					nextWaypointIndex += 1
					humanoid:MoveTo(waypoints[nextWaypointIndex].Position)
				else
					reachedConnection:Disconnect()
					blockedConnection:Disconnect()
				end
			end)
		end

		-- Initially move to second waypoint (first waypoint is path start; skip it)
		nextWaypointIndex = 2
		humanoid:MoveTo(waypoints[nextWaypointIndex].Position)
	else
		warn("Path not computed!", errorMessage)
	end
end

----------------------------------------------------------------------------------------------------
function NavPathMove.new(...)
	local self = setmetatable({}, NavPathMove)
	NavPathMove.Init(self, ...)
	return self
end

function NavPathMove:Init()
end
----------------------------------------------------------------------------------------------------
function NavPathMove:Start(navPath, chara : Model, destination)
	followPath(navPath, chara, destination)
end
----------------------------------------------------------------------------------------------------
function NavPathMove:Stop()
end
----------------------------------------------------------------------------------------------------

return NavPathMove
