return {
	TalkSequence = 1,
	CutScene = 2,
	FadeOut = 3,
	FadeIn = 4,
	WarpPlayers = 5,
	Wait = 6,
	SendSignal = 7,

	LockPlayers = 10,
	LockPlayer = 11,
	UnlockPlayers = 12,
	UnlockPlayer = 13,
	SitToSeatPlayers = 14,
	SitToSeat = 15,
	ChangeRespawnPoint = 22,
	TeleportPlace = 23,
	AwardBadgeAll = 24,
	RemoveToolAll = 25,
	ResetCamera = 30,
	FollowCameraStart = 31,
	StartFollowCameraMode = 32,
	CameraMoveTo = 33,
	ShakeCameraStart = 35,
	SetPosition = 40,
	ChangeBGMAll = 50,
	ChangeBGM = 51,
	ChangeBGMToDefault = 52,
	FadeInBGM = 60,
	FadeOutBGM = 61,
	PlaySEByName = 65,

	PlayAnimation = 67,
	StopAnimation = 68,

	ShowScreenGUI = 71,
	HideScreenGUI = 72,
	FadeInUI = 73,
	FadeInScreenGUI = 74,
	FadeOutScreenGUI = 75,
	ShowHUD = 76,
	HideHUD = 77,
	DisableProximityPrompt = 78,
	EnableProximityPrompt = 79,


	FadeOutTalker = 80,

	SendCSRemoteEvent = 90,

	--- Game専用
	FadeOutGuide = 101,
}