local items = {
{	BonusType = "Coin", Time = 180, Value = 120, },
{	BonusType = "Coin", Time = 360, Value = 120, },
{	BonusType = "Coin", Time = 540, Value = 120, },
{	BonusType = "Coin", Time = 900, Value = 120, },
{	BonusType = "Coin", Time = 1500, Value = 120, },
{	BonusType = "Coin", Time = 2100, Value = 120, },
{	BonusType = "Coin", Time = 2800, Value = 120, },
{	BonusType = "Coin", Time = 3600, Value = 120, },
{	BonusType = "Coin", Time = 7200, Value = 500, },
}
return items